export const GET_PROPERTIES_REQUEST = 'GET_PROPERTIES_REQUEST';
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTIES_FAILURE = 'GET_PROPERTIES_FAILURE';

export const CHANGE_CURRENCY_FILTER = 'CHANGE_CURRENCY_FILTER';
export const CHANGE_ROOMS_FILTER = 'CHANGE_ROOMS_FILTER';
export const CHANGE_PRICE_FILTER = 'CHANGE_PRICE_FILTER';
export const CHANGE_RATING_FILTER = 'CHANGE_RATING_FILTER';
